Repository alleycorpsur/profitline_front_ts_react-nextjs_web, pull requests merged in 2024-07, with the labels that each got.

#69 Feture/modal credit debit
  src/components/atoms/ButtonGenerateAction/ButtonGenerateAction.tsx
  src/components/atoms/ButtonGenerateAction/buttonGenerateAction.module.scss
  src/components/atoms/DividerVertical/DividerVerticalModal.tsx
  src/components/atoms/DividerVertical/dividerModal.scss
  src/components/atoms/DocumentButton/DocumentButton.tsx
  src/components/atoms/ItemsApplyModal/ItemsApplyModal.tsx
  src/components/atoms/ItemsApplyModal/itemsApplyModal.scss
  src/components/atoms/ItemsModal/ItemsActionsModal.tsx
  src/components/atoms/ItemsModal/itemsActionsModal.scss
  src/components/atoms/inputs/InputDate/InputDateForm.tsx
  src/components/atoms/inputs/InputDate/inputDateFormStyle.scss
  src/components/atoms/inputs/InputDateRange/InputDateRange.tsx
  src/components/atoms/inputs/InputDateRange/inputDateRange.scss
  src/components/atoms/inputs/InputSelect/InputSelect.tsx
  src/components/atoms/inputs/InputSelect/inputSelect.scss
  src/components/molecules/modals/ApplyAccountingAdjustment/ApplyAccountingAdjustment.tsx
  src/components/molecules/modals/ApplyAccountingAdjustment/applyAccountingAdjustment.scss
  src/components/molecules/modals/CreateAccountingAdjustment/CreateCreditNote/CreateCreditNote.tsx
  src/components/molecules/modals/CreateAccountingAdjustment/CreateCreditNote/createCreditNote.scss
  src/components/molecules/modals/CreateAccountingAdjustment/CreateDebitNote/CreateDebitNote.tsx
  src/components/molecules/modals/CreateAccountingAdjustment/CreateDebitNote/createDebitNote.scss
  src/components/molecules/modals/CreateAccountingAdjustment/CreateDiscount/CreateDiscount.tsx
  src/components/molecules/modals/CreateAccountingAdjustment/CreateDiscount/createDiscount.scss
  src/components/molecules/modals/ModalActionDiscountCredit/ModalActionDiscountCredit.tsx
  src/components/molecules/modals/ModalActionDiscountCredit/modalActionDiscountCredit.scss
  src/components/molecules/modals/ModalGenerateAction/ModalGenerateAction.tsx
  src/components/molecules/modals/ModalGenerateAction/modalgenerateaction.scss
  src/components/molecules/modals/SelectAccountingAdjustment/SelectAccountingAdjustment.tsx
  src/components/molecules/modals/SelectAccountingAdjustment/selectAccountingAdjustment.scss
  src/components/molecules/tables/InvoicesTable/InvoicesTable.tsx
  src/components/organisms/Customers/ClientsViewTable/ClientsViewTable.tsx
  src/components/organisms/Customers/WalletTab/WalletTab.tsx
  src/hooks/useAcountingAdjustment.ts
  src/hooks/useMotives.ts
  src/modules/clients/components/dashboard-expired-portfolio/dashboard-expired-portfolio.tsx
  src/modules/clients/components/wallet-tab-evidence-modal/index.ts
  src/modules/clients/components/wallet-tab-evidence-modal/wallet-tab-evidence-modal.module.scss
  src/modules/clients/components/wallet-tab-evidence-modal/wallet-tab-evidence-modal.tsx
  src/modules/clients/components/wallet-tab-payment-agreement-modal/index.ts
  src/modules/clients/components/wallet-tab-payment-agreement-modal/wallet-tab-payment-agreement-modal.module.scss
  src/modules/clients/components/wallet-tab-payment-agreement-modal/wallet-tab-payment-agreement-modal.tsx
  src/modules/clients/containers/client-details/client-details.tsx
  src/modules/clients/containers/dashboard/dashboard.tsx
  src/services/accountingAdjustment/accountingAdjustment.ts
  src/types/accountingAdjustment/IAccountingAdjustment.ts
  src/utils/utils.ts
Labels: enhancement

#81 feat: Add client status change functionality to ModalStatusClient
  src/components/molecules/modals/ModalStatusClient/ModalStatusClient.tsx
  src/components/molecules/tabs/Projects/ClientProjectForm/ClientProjectForm.tsx
  src/hooks/useClientStatus.ts
  src/services/clientTypes/clientTypes.ts
  src/services/clients/clients.ts
Labels: bug

#74 Feature/prof 285 create news
  src/components/atoms/inputs/InputDateRange/inputDateRange.scss
  src/components/molecules/modals/ApplyAccountingAdjustment/ApplyAccountingAdjustment.tsx
  src/components/molecules/modals/ApplyAccountingAdjustment/applyAccountingAdjustment.scss
  src/components/molecules/modals/CreateAccountingAdjustment/CreateCreditNote/CreateCreditNote.tsx
  src/components/molecules/modals/CreateAccountingAdjustment/CreateDebitNote/CreateDebitNote.tsx
  src/components/molecules/modals/CreateAccountingAdjustment/CreateDiscount/CreateDiscount.tsx
  src/components/molecules/modals/ModalActionDiscountCredit/ModalActionDiscountCredit.tsx
  src/components/molecules/modals/ModalActionDiscountCredit/modalActionDiscountCredit.scss
  src/components/molecules/modals/ModalGenerateAction/ModalGenerateAction.tsx
  src/components/molecules/modals/ModalGenerateAction/modalgenerateaction.scss
  src/components/molecules/modals/RegisterNews/RegisterNews.tsx
  src/components/molecules/modals/RegisterNews/registerNews.scss
  src/components/molecules/modals/SelectAccountingAdjustment/SelectAccountingAdjustment.tsx
  src/components/molecules/modals/SelectAccountingAdjustment/selectAccountingAdjustment.scss
  src/components/organisms/Customers/ClientsViewTable/ClientsViewTable.tsx
  src/components/organisms/Customers/WalletTab/WalletTab.tsx
  src/hooks/useFinancialDiscountMotives.ts
  src/hooks/useInvoiceIncidentMotives.ts
  src/hooks/useInvoices.ts
  src/modules/clients/components/wallet-tab-change-status-modal/wallet-tab-change-status-modal.module.scss
  src/modules/clients/components/wallet-tab-change-status-modal/wallet-tab-change-status-modal.tsx
  src/services/accountingAdjustment/accountingAdjustment.ts
Labels: enhancement

#90 fix: add ids in get financial-discont Update button text
  src/components/atoms/ItemsApplyModal/ItemsApplyModal.tsx
  src/components/molecules/modals/CreateAccountingAdjustment/CreateCreditNote/CreateCreditNote.tsx
  src/components/molecules/modals/CreateAccountingAdjustment/CreateDebitNote/CreateDebitNote.tsx
  src/components/molecules/modals/ModalActionDiscountCredit/ModalActionDiscountCredit.tsx
  src/components/molecules/modals/SelectAccountingAdjustment/SelectAccountingAdjustment.tsx
  src/hooks/useAcountingAdjustment.ts
Labels: bug, enhancement

#107 Feat/modal project selector
  firebase-utils.ts
  src/components/atoms/Filters/FilterUsers/FilterUsers.tsx
  src/components/molecules/SideBar/SideBar.tsx
  src/components/molecules/SideBar/sidebar.scss
  src/components/molecules/modals/ModalClientsGroup/ModalClientsGroup.tsx
  src/components/molecules/modals/ModalProjectSelector/ModalProjectSelector.tsx
  src/components/molecules/modals/ModalProjectSelector/modalProjectSelector.scss
  src/components/molecules/modals/RegisterNewsConcilation/RegisterNewsConcilation.tsx
  src/components/molecules/selects/SelectStructure/SelectStructure.tsx
  src/components/molecules/selects/SelectZone/SelectZone.tsx
  src/components/molecules/tables/ConcilationTables/PasteConcilationTable/PasteConcilationTable.tsx
  src/components/molecules/tables/ProjectsTable/ProjectsTable.tsx
  src/components/molecules/tabs/Projects/UserProjectForm/UserProjectForm.tsx
  src/components/organisms/Customers/ClientsViewTable/ClientsViewTable.tsx
  src/components/organisms/discounts/create/components/annualDiscountDefinition/AnnualDiscountDefinition.tsx
  src/components/organisms/discounts/create/components/annualDiscountDefinition/annualFeatures/hooks/useAnnualFeatures.ts
  src/components/organisms/discounts/create/components/definitionsDiscount/feats/hooks/useDiscountFeats.ts
  src/components/organisms/discounts/create/hooks/useCreateDiscountView.ts
  src/components/organisms/discounts/hooks/useDiscount.ts
  src/components/organisms/discounts/wrapper/DiscountWrapper.tsx
  src/components/organisms/header/header.tsx
  src/hooks/useBusinessRules.ts
  src/hooks/useClientGroup.ts
  src/hooks/useClientTypes.ts
  src/hooks/useClientsGroups.ts
  src/hooks/useDocumentByClient.ts
  src/hooks/useHolding.ts
  src/hooks/useLocations.ts
  src/hooks/useModalUploadDocument.ts
  src/hooks/usePortfolios.ts
  src/hooks/useProject.ts
  src/hooks/useShipTo.ts
  src/hooks/useZone.ts
  src/lib/slices/createProjectSlice.ts
  src/lib/store/store.ts
  src/services/permissions/userPermissions.tsx
  src/types/userPermissions/IUserPermissions.tsx
Labels: enhancement

#112 Prof 410 detalle de factura
  src/components/molecules/modals/FileDownloadModal/FileDownloadModal.tsx
  src/components/molecules/tables/ConcilationTables/ConcilationTable/ConcilationTable.tsx
  src/components/molecules/tables/ConcilationTables/PasteConcilationTable/PasteConcilationTable.tsx
  src/hooks/useProjects.ts
  src/modules/clients/components/invoice-download-modal/invoice-download-modal.module.scss
  src/modules/clients/components/invoice-download-modal/invoice-download-modal.tsx
  src/modules/clients/components/wallet-tab-change-status-modal/wallet-tab-change-status-modal.tsx
  src/modules/clients/containers/dashboard/dashboard.tsx
  src/modules/clients/containers/invoice-detail-modal/invoice-detail-modal.module.scss
  src/modules/clients/containers/invoice-detail-modal/invoice-detail-modal.tsx
  src/services/concilation/concilation.ts
Labels: bug, enhancement

#120 fix: update login page title and remove unnecessary image logo
  public/images/login/01-example-login-logo.png
  public/images/login/CashPort.png
  src/components/organisms/auth/login/Login.tsx
  src/components/organisms/auth/login/login.module.scss
Labels: enhancement
